name: "SomeName"

trigger:
- master
- feature/*

pool:
  vmImage: ubuntu-latest
  name: bootcamp-pool

variables:
  YOURVARKEYS: YOURVARVALUES  

stages:

# Continuous Integration Process
- stage: CI
  jobs:
  - job: BuildAndPushDocker
    workspace: 
      clean: all
    steps:
    - bash: echo "Hello world"
